create table product (
    id integer generated by default as identity,
    name varchar(255),
    description varchar(255),
    price numeric(38,2),
    weight float(53),
    image_url varchar(255),
    category_id integer,
    supplier_id integer,
    primary key (id),
    foreign key (category_id) references product_category,
    foreign key (supplier_id) references supplier
)