create table customer (
    id integer generated by default as identity,
    first_name varchar(255),
    last_name varchar(255),
    username varchar(255),
    password varchar(255),
    email_address varchar(255),
    primary key (id)
)
