create table revenue (
    id integer generated by default as identity,
    local_date timestamp(0),
    sum numeric(38,2),
    location_id integer,
    primary key (id),
    foreign key (location_id) references location
)