create table orders (
    id integer generated by default as identity,
    shipped_from_id integer,
    customer_id integer,
    created_at timestamp(0),
    country_address varchar(255),
    city_address varchar(255),
    province_address varchar(255),
    street_address varchar(255),
    primary key (id),
    foreign key (customer_id) references customer,
    foreign key (shipped_from_id) references location
)
